[package]
name = "day9pt1"
version = "0.1.0"
authors = ["Murray Rogers <murray.rogers@metaswitch.com>"]
edition = "2018"
publish = ["metaswitch"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
